spring:
  data:
    mongodb:
      database: orderservice
      uri: mongodb+srv://preethi:root@cluster0.2m31f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  application:
    name: order-service

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
